# Generated by Django 4.2.2 on 2023-10-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goodscategory', models.CharField(choices=[('Electronics', 'Electronics'), ('Fasion', 'Fasion'), ('Accessories', 'Accessories'), ('Books', 'Books'), ('Home Appliances', 'Home Appliances'), ('Food packets', 'Food packets')], default='Accessories', max_length=200)),
                ('weight', models.FloatField()),
                ('kilometer', models.IntegerField()),
            ],
        ),
    ]
