# Generated by Django 4.2.2 on 2023-10-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kilometer',
        ),
    ]
