# Generated by Django 4.2.2 on 2023-10-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_product_kilometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kilo_meter',
            field=models.IntegerField(default=1, verbose_name='Distance in Kilometer'),
        ),
    ]
