# Generated by Django 4.2.2 on 2023-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_shipmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmodel',
            name='fr_name',
            field=models.CharField(max_length=30, verbose_name='enter name'),
        ),
    ]
