# Generated by Django 4.2.2 on 2023-10-10 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_shipmodel_fr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmodel',
            name='fr_district',
            field=models.CharField(choices=[('choose district', 'choose district'), ('kasarkode', 'kasarkode'), ('kannur', 'kannur'), ('kozhikode', 'kozhikode'), ('malappuram', 'malappuram'), ('wayanad', 'wayanad'), ('palakkad', 'palakkad'), ('idukki', 'idukki'), ('thrissur', 'thrissur'), ('eranakulam', 'eranakulam'), ('alappuzha', 'alappuzha'), ('pathanamthitta', 'pathanamthitta'), ('kollam', 'kollam'), ('kottayam', 'kottayam'), ('thiruvananthapuram', 'thiruvananthapuram')], default='choose district', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipmodel',
            name='fr_phone',
            field=models.IntegerField(verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='shipmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.product'),
        ),
        migrations.AlterField(
            model_name='shipmodel',
            name='to_district',
            field=models.CharField(choices=[('choose district', 'choose district'), ('kasarkode', 'kasarkode'), ('kannur', 'kannur'), ('kozhikode', 'kozhikode'), ('malappuram', 'malappuram'), ('wayanad', 'wayanad'), ('palakkad', 'palakkad'), ('idukki', 'idukki'), ('thrissur', 'thrissur'), ('eranakulam', 'eranakulam'), ('alappuzha', 'alappuzha'), ('pathanamthitta', 'pathanamthitta'), ('kollam', 'kollam'), ('kottayam', 'kottayam'), ('thiruvananthapuram', 'thiruvananthapuram')], default='choose district', max_length=100),
        ),
    ]
